export interface Seller {
  id: string;
  name: string;
  city: string;
  province: string;
  rating: number;
  totalSales: number;
  badge?: "star" | "top" | "trusted";
  verified: boolean;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  categorySlug: string;
  seller: Seller;
  rating: number;
  reviewCount: number;
  soldCount: number;
  stock: number;
  weight: number;
  tags: string[];
  isNew?: boolean;
  isFeatured?: boolean;
  isSponsored?: boolean;
}

export interface Category {
  name: string;
  slug: string;
  icon: string;
  count: number;
}

// ── Sellers ───────────────────────────────────────────────────────────────────

const sellers: Record<string, Seller> = {
  s01: { id: "s01", name: "Dapur Bu Ratna", city: "Padang", province: "Sumatera Barat", rating: 4.9, totalSales: 2340, badge: "star", verified: true },
  s02: { id: "s02", name: "Keripik Pak Budi", city: "Malang", province: "Jawa Timur", rating: 4.8, totalSales: 1876, badge: "top", verified: true },
  s03: { id: "s03", name: "Kopi Nusantara", city: "Takengon", province: "Aceh", rating: 4.9, totalSales: 3120, badge: "star", verified: true },
  s04: { id: "s04", name: "Sambal Legendaris", city: "Surabaya", province: "Jawa Timur", rating: 4.7, totalSales: 987, badge: "trusted", verified: true },
  s05: { id: "s05", name: "Oleh-oleh Garut", city: "Garut", province: "Jawa Barat", rating: 4.6, totalSales: 754, verified: true },
  s06: { id: "s06", name: "Batik Solo Asri", city: "Solo", province: "Jawa Tengah", rating: 4.9, totalSales: 4210, badge: "star", verified: true },
  s07: { id: "s07", name: "Kebaya Bandung Modern", city: "Bandung", province: "Jawa Barat", rating: 4.8, totalSales: 1560, badge: "top", verified: true },
  s08: { id: "s08", name: "Tenun NTT Authentic", city: "Kupang", province: "NTT", rating: 4.7, totalSales: 632, verified: true },
  s09: { id: "s09", name: "Jepara Wood Art", city: "Jepara", province: "Jawa Tengah", rating: 4.9, totalSales: 2890, badge: "star", verified: true },
  s10: { id: "s10", name: "Keramik Lombok", city: "Mataram", province: "NTB", rating: 4.6, totalSales: 445, verified: true },
  s11: { id: "s11", name: "Rotan Bali Premium", city: "Denpasar", province: "Bali", rating: 4.8, totalSales: 1230, badge: "trusted", verified: true },
  s12: { id: "s12", name: "Perak Koto Gadang", city: "Bukittinggi", province: "Sumatera Barat", rating: 4.9, totalSales: 876, badge: "star", verified: true },
  s13: { id: "s13", name: "Herbal Nusantara", city: "Yogyakarta", province: "DIY", rating: 4.7, totalSales: 2100, badge: "trusted", verified: true },
  s14: { id: "s14", name: "Madu Borneo", city: "Pontianak", province: "Kalimantan Barat", rating: 4.8, totalSales: 1450, badge: "top", verified: true },
  s15: { id: "s15", name: "Rempah Mama Makassar", city: "Makassar", province: "Sulawesi Selatan", rating: 4.7, totalSales: 678, verified: true },
  s16: { id: "s16", name: "Kuliner Solo Enak", city: "Solo", province: "Jawa Tengah", rating: 4.8, totalSales: 1234, badge: "trusted", verified: true },
  s17: { id: "s17", name: "Snack Lampung", city: "Bandar Lampung", province: "Lampung", rating: 4.5, totalSales: 543, verified: true },
  s18: { id: "s18", name: "Batik Pekalongan Jaya", city: "Pekalongan", province: "Jawa Tengah", rating: 4.8, totalSales: 3400, badge: "star", verified: true },
  s19: { id: "s19", name: "Fashion Tenun Lombok", city: "Mataram", province: "NTB", rating: 4.7, totalSales: 892, verified: true },
  s20: { id: "s20", name: "Kerajinan Batok", city: "Yogyakarta", province: "DIY", rating: 4.6, totalSales: 321, verified: true },
  s21: { id: "s21", name: "Kecantikan Alami", city: "Bandung", province: "Jawa Barat", rating: 4.8, totalSales: 1678, badge: "top", verified: true },
  s22: { id: "s22", name: "Apotek Herbal Jamu", city: "Surakarta", province: "Jawa Tengah", rating: 4.7, totalSales: 945, verified: true },
  s23: { id: "s23", name: "Elektronik UMKM", city: "Tangerang", province: "Banten", rating: 4.5, totalSales: 1102, verified: true },
  s24: { id: "s24", name: "Makanan Khas Manado", city: "Manado", province: "Sulawesi Utara", rating: 4.8, totalSales: 765, badge: "trusted", verified: true },
  s25: { id: "s25", name: "Sentra Gerabah Kasongan", city: "Bantul", province: "DIY", rating: 4.7, totalSales: 534, verified: true },
  s26: { id: "s26", name: "Batik Mega Mendung", city: "Cirebon", province: "Jawa Barat", rating: 4.9, totalSales: 2120, badge: "star", verified: true },
  s27: { id: "s27", name: "Toko Abon Solo", city: "Solo", province: "Jawa Tengah", rating: 4.8, totalSales: 987, badge: "trusted", verified: true },
  s28: { id: "s28", name: "Minuman Kesehatan", city: "Jakarta Selatan", province: "DKI Jakarta", rating: 4.6, totalSales: 1320, verified: true },
  s29: { id: "s29", name: "Aksesori Gadget Lokal", city: "Bekasi", province: "Jawa Barat", rating: 4.4, totalSales: 876, verified: true },
  s30: { id: "s30", name: "Songket Palembang", city: "Palembang", province: "Sumatera Selatan", rating: 4.9, totalSales: 1450, badge: "star", verified: true },
};

// ── Products ──────────────────────────────────────────────────────────────────

function img(id: string) {
  return `https://picsum.photos/seed/${id}/400/400`;
}

export const products: Product[] = [
  // ── Makanan & Minuman ────────────────────────────────────────────────────────
  { id: "mkm001", name: "Rendang Daging Sapi Premium", slug: "rendang-daging-sapi-premium", description: "Rendang daging sapi asli Padang dimasak 6 jam dengan 40+ rempah pilihan. Tahan 1 bulan suhu ruang, 6 bulan dalam freezer.", price: 95000, originalPrice: 115000, image: img("mkm001"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s01, rating: 4.9, reviewCount: 1243, soldCount: 8900, stock: 150, weight: 250, tags: ["rendang", "padang", "daging", "halal"], isFeatured: true, isSponsored: true },
  { id: "mkm002", name: "Keripik Tempe Malang Original 250gr", slug: "keripik-tempe-malang-original", description: "Keripik tempe gurih renyah dari Malang. Dibuat dari tempe segar pilihan, digoreng dengan teknik khusus agar tetap krispy lama.", price: 28000, image: img("mkm002"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s02, rating: 4.8, reviewCount: 876, soldCount: 12400, stock: 500, weight: 250, tags: ["keripik", "tempe", "malang", "cemilan"], isFeatured: true },
  { id: "mkm003", name: "Kopi Arabika Gayo Aceh 250gr", slug: "kopi-arabika-gayo-aceh-250gr", description: "Kopi Arabika single origin dari dataran tinggi Gayo, Aceh. Proses natural, rasa fruity dengan aroma floral yang khas.", price: 75000, originalPrice: 90000, image: img("mkm003"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s03, rating: 4.9, reviewCount: 2145, soldCount: 15600, stock: 300, weight: 250, tags: ["kopi", "arabika", "gayo", "aceh"], isFeatured: true, isSponsored: true },
  { id: "mkm004", name: "Sambal Bawang Bu Rudy Extra Pedas", slug: "sambal-bawang-bu-rudy-extra-pedas", description: "Sambal bawang legendaris Surabaya dengan level kepedasan ekstra. Cocok sebagai pelengkap nasi, ayam goreng, atau lalapan.", price: 32000, image: img("mkm004"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s04, rating: 4.7, reviewCount: 654, soldCount: 7800, stock: 200, weight: 150, tags: ["sambal", "pedas", "surabaya"], isNew: true },
  { id: "mkm005", name: "Dodol Garut Original 500gr", slug: "dodol-garut-original", description: "Dodol Garut asli yang legit dan kenyal. Terbuat dari ketan hitam pilihan dengan gula aren asli dari Garut.", price: 45000, image: img("mkm005"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s05, rating: 4.6, reviewCount: 432, soldCount: 5400, stock: 180, weight: 500, tags: ["dodol", "garut", "ketan", "oleh-oleh"] },
  { id: "mkm006", name: "Abon Sapi Crispy Solo Istimewa", slug: "abon-sapi-crispy-solo", description: "Abon sapi khas Solo dengan tekstur crispy dan rasa yang gurih manis. Cocok untuk lauk nasi atau isi risoles.", price: 55000, originalPrice: 65000, image: img("mkm006"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s27, rating: 4.8, reviewCount: 789, soldCount: 9200, stock: 250, weight: 200, tags: ["abon", "sapi", "solo", "lauk"] },
  { id: "mkm007", name: "Kopi Robusta Flores 500gr", slug: "kopi-robusta-flores-500gr", description: "Kopi Robusta dari pegunungan Flores dengan body kuat dan rasa cokelat bittersweet. Sempurna untuk espresso dan kopi susu.", price: 85000, image: img("mkm007"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s03, rating: 4.8, reviewCount: 987, soldCount: 6700, stock: 200, weight: 500, tags: ["kopi", "robusta", "flores", "ntt"] },
  { id: "mkm008", name: "Kerupuk Ikan Bangka Belitung", slug: "kerupuk-ikan-bangka", description: "Kerupuk ikan khas Bangka Belitung terbuat dari ikan tenggiri segar. Renyah dan penuh cita rasa seafood asli.", price: 35000, image: img("mkm008"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s24, rating: 4.7, reviewCount: 543, soldCount: 4300, stock: 300, weight: 300, tags: ["kerupuk", "ikan", "bangka"] },
  { id: "mkm009", name: "Bakpia Pathuk Yogyakarta Isi Kacang Hijau", slug: "bakpia-pathuk-yogyakarta", description: "Bakpia Pathuk legendaris Yogyakarta dengan isian kacang hijau manis. Kulit tipis, isian melimpah, langsung dari produsen.", price: 42000, image: img("mkm009"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s16, rating: 4.8, reviewCount: 1102, soldCount: 11000, stock: 400, weight: 400, tags: ["bakpia", "yogyakarta", "oleh-oleh"] },
  { id: "mkm010", name: "Gudeg Kaleng Jogja Bu Tjitro", slug: "gudeg-kaleng-jogja", description: "Gudeg nangka asli Jogja dalam kemasan kaleng steril. Tahan 1 tahun, bisa kirim ke seluruh Indonesia tanpa khawatir basi.", price: 38000, image: img("mkm010"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s16, rating: 4.7, reviewCount: 876, soldCount: 7600, stock: 350, weight: 300, tags: ["gudeg", "jogja", "kaleng"] },
  { id: "mkm011", name: "Cakalang Fufu Manado", slug: "cakalang-fufu-manado", description: "Ikan cakalang asap khas Manado yang diasap tradisional dengan kayu tertentu. Kaya protein, tahan 2 minggu.", price: 65000, image: img("mkm011"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s24, rating: 4.8, reviewCount: 654, soldCount: 3900, stock: 120, weight: 300, tags: ["ikan", "manado", "cakalang"], isNew: true },
  { id: "mkm012", name: "Brownies Kukus Amanda Bandung", slug: "brownies-kukus-amanda", description: "Brownies kukus lembut dan moist ala Amanda Bandung. Terbuat dari coklat premium dengan tekstur yang legit dan tidak terlalu manis.", price: 58000, originalPrice: 70000, image: img("mkm012"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s07, rating: 4.9, reviewCount: 1543, soldCount: 13000, stock: 100, weight: 500, tags: ["brownies", "bandung", "coklat"], isFeatured: true },
  { id: "mkm013", name: "Keripik Pisang Lampung Coklat", slug: "keripik-pisang-lampung-coklat", description: "Keripik pisang manis-gurih dilapisi coklat susu premium. Produk andalan dari Lampung dengan bahan baku pisang lokal segar.", price: 25000, image: img("mkm013"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s17, rating: 4.6, reviewCount: 432, soldCount: 6700, stock: 400, weight: 250, tags: ["keripik", "pisang", "lampung", "coklat"] },
  { id: "mkm014", name: "Gepuk Sapi Bandung Premium", slug: "gepuk-sapi-bandung", description: "Daging sapi yang dimemarkan dan dimasak dengan bumbu manis gurih khas Sunda. Cocok untuk bekal dan oleh-oleh.", price: 72000, image: img("mkm014"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s07, rating: 4.7, reviewCount: 567, soldCount: 4500, stock: 130, weight: 200, tags: ["gepuk", "daging", "bandung", "sunda"] },
  { id: "mkm015", name: "Kopi Luwak Asli Sumatra 100gr", slug: "kopi-luwak-asli-sumatra", description: "Kopi luwak autentik dari Sumatera. Proses fermentasi alami oleh musang luwak menghasilkan kopi paling eksklusif dunia.", price: 285000, originalPrice: 350000, image: img("mkm015"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s03, rating: 4.9, reviewCount: 321, soldCount: 870, stock: 50, weight: 100, tags: ["kopi", "luwak", "premium", "sumatra"], isFeatured: true, isSponsored: true },
  { id: "mkm016", name: "Sambal Matah Bali Segar", slug: "sambal-matah-bali", description: "Sambal matah Bali dengan bahan segar — serai, bawang merah, cabai rawit, dan minyak kelapa. Dikirim dalam kondisi segar.", price: 28000, image: img("mkm016"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s11, rating: 4.8, reviewCount: 765, soldCount: 5600, stock: 200, weight: 150, tags: ["sambal", "bali", "matah", "segar"] },
  { id: "mkm017", name: "Tape Ketan Hitam Bandung", slug: "tape-ketan-hitam-bandung", description: "Tape ketan hitam fermentasi alami dari Bandung. Manis asam segar dengan aroma khas yang menggugah selera.", price: 22000, image: img("mkm017"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s07, rating: 4.5, reviewCount: 234, soldCount: 3200, stock: 200, weight: 300, tags: ["tape", "ketan", "bandung"] },
  { id: "mkm018", name: "Emping Melinjo Banten Original", slug: "emping-melinjo-banten", description: "Emping melinjo khas Banten yang tipis dan renyah. Dibuat secara tradisional dari biji melinjo pilihan tanpa bahan pengawet.", price: 32000, image: img("mkm018"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s17, rating: 4.6, reviewCount: 345, soldCount: 4100, stock: 300, weight: 200, tags: ["emping", "melinjo", "banten"] },
  { id: "mkm019", name: "Rengginang Udang Rebon", slug: "rengginang-udang-rebon", description: "Rengginang ketan dengan campuran udang rebon yang gurih. Produk tradisional Jawa yang digoreng renyah tanpa pengawet.", price: 30000, image: img("mkm019"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s15, rating: 4.6, reviewCount: 287, soldCount: 3800, stock: 250, weight: 250, tags: ["rengginang", "udang", "ketan"] },
  { id: "mkm020", name: "Kopi Toraja Single Origin 200gr", slug: "kopi-toraja-single-origin", description: "Kopi arabika dari Tana Toraja dengan proses washed. Rasa bersih, body medium, dengan aftertaste caramel yang panjang.", price: 85000, image: img("mkm020"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s15, rating: 4.8, reviewCount: 543, soldCount: 3100, stock: 150, weight: 200, tags: ["kopi", "toraja", "arabika"], isNew: true },
  { id: "mkm021", name: "Peyek Kacang Renyah Crispy", slug: "peyek-kacang-crispy", description: "Peyek kacang tanah super renyah dengan bumbu bawang ketumbar khas. Cocok untuk camilan atau pelengkap nasi.", price: 18000, image: img("mkm021"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s16, rating: 4.7, reviewCount: 543, soldCount: 7800, stock: 500, weight: 200, tags: ["peyek", "kacang", "cemilan"] },
  { id: "mkm022", name: "Serundeng Kelapa Pedas Manis", slug: "serundeng-kelapa", description: "Serundeng kelapa parut yang digoreng kering dengan bumbu ketumbar dan gula aren. Tahan lama dan cocok sebagai pelengkap lauk.", price: 25000, image: img("mkm022"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s01, rating: 4.6, reviewCount: 234, soldCount: 3400, stock: 300, weight: 200, tags: ["serundeng", "kelapa", "lauk"] },
  { id: "mkm023", name: "Wajik Ketan Bandung Gula Merah", slug: "wajik-ketan-bandung", description: "Wajik ketan Bandung dengan gula merah aren asli. Manis legit dengan aroma pandan dan kelapa yang harum.", price: 35000, image: img("mkm023"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s07, rating: 4.7, reviewCount: 312, soldCount: 2900, stock: 180, weight: 300, tags: ["wajik", "ketan", "bandung"] },
  { id: "mkm024", name: "Dendeng Balado Sapi Padang", slug: "dendeng-balado-padang", description: "Dendeng sapi iris tipis dengan bumbu balado cabai merah Padang. Pedas menggigit, gurih, dan tahan hingga 2 minggu.", price: 85000, originalPrice: 100000, image: img("mkm024"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s01, rating: 4.8, reviewCount: 654, soldCount: 5200, stock: 120, weight: 200, tags: ["dendeng", "padang", "sapi", "pedas"] },
  { id: "mkm025", name: "Teh Hijau Organik Jawa 100gr", slug: "teh-hijau-organik-jawa", description: "Teh hijau organik dari perkebunan teh Jawa tanpa pestisida. Kaya antioksidan, rasa segar, aroma bunga yang natural.", price: 45000, image: img("mkm025"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s13, rating: 4.7, reviewCount: 432, soldCount: 4600, stock: 200, weight: 100, tags: ["teh", "hijau", "organik", "herbal"] },
  { id: "mkm026", name: "Sambel Geprek Frozen 10 Pcs", slug: "sambel-geprek-frozen", description: "Ayam geprek dengan sambal bawang extra pedas dalam kemasan frozen siap masak. Praktis, halal, tanpa MSG.", price: 55000, image: img("mkm026"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s04, rating: 4.6, reviewCount: 345, soldCount: 4100, stock: 100, weight: 500, tags: ["geprek", "ayam", "frozen", "pedas"], isNew: true },
  { id: "mkm027", name: "Stik Keju Homemade 200gr", slug: "stik-keju-homemade", description: "Stik keju buatan rumahan dengan keju cheddar melimpah. Renyah, gurih, cocok untuk cemilan keluarga.", price: 32000, image: img("mkm027"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s05, rating: 4.6, reviewCount: 287, soldCount: 5600, stock: 300, weight: 200, tags: ["stik", "keju", "cemilan"] },
  { id: "mkm028", name: "Kue Semprong Wijen Khas Betawi", slug: "kue-semprong-wijen", description: "Kue semprong tipis renyah khas Betawi dengan taburan wijen. Dibuat tradisional dengan cetakan besi, aroma pandan yang harum.", price: 28000, image: img("mkm028"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s28, rating: 4.7, reviewCount: 234, soldCount: 3200, stock: 250, weight: 200, tags: ["kue", "semprong", "betawi"] },
  { id: "mkm029", name: "Selai Nanas Homemade 200gr", slug: "selai-nanas-homemade", description: "Selai nanas buatan sendiri tanpa pengawet buatan. Manis asam alami, cocok untuk roti, kue, atau croissant.", price: 22000, image: img("mkm029"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s17, rating: 4.5, reviewCount: 187, soldCount: 2800, stock: 200, weight: 200, tags: ["selai", "nanas", "homemade"] },
  { id: "mkm030", name: "Mochi Ice Cream Sukabumi", slug: "mochi-ice-cream-sukabumi", description: "Mochi lembut isi es krim khas Sukabumi. Tersedia rasa durian, strawberry, coklat, dan matcha. Dikirim dengan dry ice.", price: 65000, image: img("mkm030"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s07, rating: 4.8, reviewCount: 876, soldCount: 6700, stock: 80, weight: 300, tags: ["mochi", "ice cream", "sukabumi"], isNew: true },
  { id: "mkm031", name: "Manisan Buah Kering Cianjur", slug: "manisan-buah-kering-cianjur", description: "Manisan buah kering aneka rasa — mangga, salak, ceremai — khas Cianjur. Manis asam segar tanpa bahan kimia berbahaya.", price: 35000, image: img("mkm031"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s05, rating: 4.5, reviewCount: 213, soldCount: 3100, stock: 200, weight: 300, tags: ["manisan", "buah", "cianjur"] },
  { id: "mkm032", name: "Kripik Pare Crispy Pedas Manis", slug: "kripik-pare-pedas-manis", description: "Keripik pare unik dengan rasa pedas manis yang adiktif. Tinggi nutrisi, rendah kalori, camilan sehat yang berbeda.", price: 20000, image: img("mkm032"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s13, rating: 4.4, reviewCount: 145, soldCount: 2200, stock: 300, weight: 150, tags: ["keripik", "pare", "sehat"] },
  { id: "mkm033", name: "Keripik Bayam Renyah 100gr", slug: "keripik-bayam-renyah", description: "Keripik bayam segar yang digoreng renyah sempurna tanpa MSG. Camilan sehat kaya zat besi dan vitamin.", price: 18000, image: img("mkm033"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s13, rating: 4.5, reviewCount: 198, soldCount: 3400, stock: 400, weight: 100, tags: ["keripik", "bayam", "sehat"] },
  { id: "mkm034", name: "Rempeyek Udang Rebon Gurih", slug: "rempeyek-udang-rebon", description: "Rempeyek tipis renyah dengan udang rebon kecil yang gurih. Cocok sebagai pelengkap nasi atau camilan sore hari.", price: 28000, image: img("mkm034"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s15, rating: 4.6, reviewCount: 267, soldCount: 4500, stock: 300, weight: 200, tags: ["rempeyek", "udang"] },
  { id: "mkm035", name: "Kopi Sindoro Sumbing Jawa 200gr", slug: "kopi-sindoro-sumbing", description: "Kopi arabika dari lereng Gunung Sindoro dan Sumbing, Jawa Tengah. Rasa cokelat kacang, body medium, proses honey.", price: 78000, image: img("mkm035"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s16, rating: 4.8, reviewCount: 432, soldCount: 2100, stock: 150, weight: 200, tags: ["kopi", "jawa", "arabika"], isNew: true },
  { id: "mkm036", name: "Bolu Kukus Pandan Lembut", slug: "bolu-kukus-pandan", description: "Bolu kukus pandan lembut dan harum dibuat setiap hari. Tanpa bahan pengawet, tekstur fluffy dan ringan.", price: 35000, image: img("mkm036"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s28, rating: 4.7, reviewCount: 345, soldCount: 5100, stock: 80, weight: 300, tags: ["bolu", "pandan", "kukus"] },
  { id: "mkm037", name: "Jus Lidah Buaya Murni 500ml", slug: "jus-lidah-buaya-murni", description: "Jus lidah buaya murni dari Pontianak tanpa gula tambahan. Menyegarkan, baik untuk pencernaan dan kulit.", price: 30000, image: img("mkm037"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s28, rating: 4.6, reviewCount: 213, soldCount: 2900, stock: 150, weight: 500, tags: ["jus", "lidah buaya", "sehat"] },
  { id: "mkm038", name: "Tempe Mendoan Purwokerto Frozen", slug: "tempe-mendoan-frozen", description: "Tempe mendoan khas Purwokerto dalam kemasan frozen. Lembut di dalam, sedikit crispy di luar. Sajian 10 pcs per pack.", price: 40000, image: img("mkm038"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s16, rating: 4.7, reviewCount: 432, soldCount: 5800, stock: 120, weight: 400, tags: ["tempe", "mendoan", "frozen"] },
  { id: "mkm039", name: "Kopi Bajawa Flores NTT 200gr", slug: "kopi-bajawa-flores", description: "Kopi arabika Bajawa dari Flores NTT dengan proses full wash. Citarasa buah tropis, keasaman cerah, body ringan.", price: 80000, image: img("mkm039"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s15, rating: 4.8, reviewCount: 321, soldCount: 1800, stock: 100, weight: 200, tags: ["kopi", "bajawa", "ntt", "flores"] },
  { id: "mkm040", name: "Keripik Singkong Pedas Level 5", slug: "keripik-singkong-pedas", description: "Keripik singkong super renyah dengan tingkat kepedasan level 5. Dibuat dari singkong segar, digoreng tanpa MSG.", price: 22000, image: img("mkm040"), category: "Makanan & Minuman", categorySlug: "makanan-minuman", seller: sellers.s17, rating: 4.7, reviewCount: 654, soldCount: 8900, stock: 500, weight: 200, tags: ["keripik", "singkong", "pedas"] },

  // ── Fashion & Batik ──────────────────────────────────────────────────────────
  { id: "fas001", name: "Batik Tulis Solo Motif Parang Rusak", slug: "batik-tulis-solo-parang-rusak", description: "Batik tulis tangan asli Solo dengan motif parang rusak klasik. Kain primisima 100%, dikerjakan oleh pengrajin batik berpengalaman.", price: 450000, originalPrice: 550000, image: img("fas001"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.9, reviewCount: 432, soldCount: 1200, stock: 50, weight: 300, tags: ["batik", "tulis", "solo", "motif parang"], isFeatured: true, isSponsored: true },
  { id: "fas002", name: "Kemeja Batik Pria Lengan Panjang Kantor", slug: "kemeja-batik-pria-kantor", description: "Kemeja batik formal untuk pria dengan bahan katun nyaman. Cocok untuk acara kantor, pernikahan, dan formal lainnya.", price: 185000, image: img("fas002"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.8, reviewCount: 765, soldCount: 3400, stock: 100, weight: 400, tags: ["batik", "kemeja", "pria", "kantor"] },
  { id: "fas003", name: "Kebaya Modern Brokat Wanita", slug: "kebaya-modern-brokat", description: "Kebaya modern berbahan brokat premium dengan potongan elegan. Cocok untuk wisuda, pernikahan, dan acara formal.", price: 320000, originalPrice: 400000, image: img("fas003"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s07, rating: 4.9, reviewCount: 543, soldCount: 980, stock: 40, weight: 500, tags: ["kebaya", "brokat", "wanita", "formal"], isFeatured: true },
  { id: "fas004", name: "Dress Batik Jumputan Wanita", slug: "dress-batik-jumputan", description: "Dress batik jumputan dengan motif abstrak yang unik dan elegan. Bahan rayon lembut, nyaman dipakai sepanjang hari.", price: 245000, image: img("fas004"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s18, rating: 4.7, reviewCount: 432, soldCount: 1560, stock: 70, weight: 400, tags: ["dress", "batik", "jumputan", "wanita"] },
  { id: "fas005", name: "Tenun Ikat NTT Motif Tradisional", slug: "tenun-ikat-ntt-tradisional", description: "Kain tenun ikat handmade dari NTT dengan motif binatang dan alam khas Flores. Setiap lembar berbeda dan tidak ada yang persis sama.", price: 385000, image: img("fas005"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s08, rating: 4.9, reviewCount: 210, soldCount: 450, stock: 25, weight: 600, tags: ["tenun", "ikat", "ntt", "handmade"], isFeatured: true },
  { id: "fas006", name: "Jaket Batik Pria Casual Modern", slug: "jaket-batik-pria-casual", description: "Jaket batik pria dengan desain modern yang memadukan motif batik klasik dan potongan kontemporer. Bahan denim batik yang kuat.", price: 295000, originalPrice: 350000, image: img("fas006"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.7, reviewCount: 345, soldCount: 890, stock: 60, weight: 700, tags: ["jaket", "batik", "pria", "casual"] },
  { id: "fas007", name: "Blouse Batik Wanita Lengan Balon", slug: "blouse-batik-lengan-balon", description: "Blouse batik wanita dengan lengan balon yang feminin. Motif batik mega mendung Cirebon, bahan katun premium.", price: 165000, image: img("fas007"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s26, rating: 4.7, reviewCount: 543, soldCount: 2300, stock: 80, weight: 350, tags: ["blouse", "batik", "wanita"] },
  { id: "fas008", name: "Sarung Batik Pria Premium", slug: "sarung-batik-pria-premium", description: "Sarung batik cap khas Pekalongan untuk pria. Bahan katun halus, motif tradisional, cocok untuk sholat dan acara adat.", price: 125000, image: img("fas008"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s18, rating: 4.8, reviewCount: 654, soldCount: 4100, stock: 150, weight: 400, tags: ["sarung", "batik", "pekalongan"] },
  { id: "fas009", name: "Rok Tenun Bali Motif Endek", slug: "rok-tenun-bali-endek", description: "Rok tenun Bali berbahan endek dengan motif klasik Bali. Jatuh anggun di tubuh, cocok untuk casual maupun semi-formal.", price: 210000, image: img("fas009"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s11, rating: 4.8, reviewCount: 321, soldCount: 1200, stock: 55, weight: 400, tags: ["rok", "tenun", "bali", "endek"] },
  { id: "fas010", name: "Gamis Batik Syar'i Motif Kawung", slug: "gamis-batik-syari-kawung", description: "Gamis batik syar'i untuk wanita muslimah dengan motif kawung klasik. Bahan katun adem, longgar, cocok harian dan acara.", price: 275000, originalPrice: 320000, image: img("fas010"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s18, rating: 4.8, reviewCount: 876, soldCount: 2900, stock: 70, weight: 500, tags: ["gamis", "batik", "muslimah", "syari"] },
  { id: "fas011", name: "Koko Batik Pria Lengan Pendek", slug: "koko-batik-pria-lengan-pendek", description: "Baju koko batik untuk pria dengan lengan pendek. Motif batik halus, nyaman dipakai sholat Jumat atau acara religi.", price: 145000, image: img("fas011"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.7, reviewCount: 432, soldCount: 2800, stock: 120, weight: 350, tags: ["koko", "batik", "pria", "muslim"] },
  { id: "fas012", name: "Hijab Batik Segiempat Premium", slug: "hijab-batik-segiempat", description: "Hijab batik segiempat berbahan voal premium dengan motif batik modern. Nyaman, mudah dibentuk, cocok untuk keseharian.", price: 85000, image: img("fas012"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s18, rating: 4.8, reviewCount: 765, soldCount: 5600, stock: 200, weight: 150, tags: ["hijab", "batik", "wanita"] },
  { id: "fas013", name: "Kemeja Lurik Solo Lengan Panjang", slug: "kemeja-lurik-solo", description: "Kemeja lurik tradisional Solo dengan bahan ATBM (Alat Tenun Bukan Mesin). Motif garis-garis halus yang elegan dan klasik.", price: 195000, image: img("fas013"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.8, reviewCount: 312, soldCount: 980, stock: 60, weight: 400, tags: ["lurik", "kemeja", "solo", "tenun"] },
  { id: "fas014", name: "Tenun Ulos Batak Sumatra Utara", slug: "tenun-ulos-batak", description: "Kain ulos Batak handmade dari Sumatera Utara. Simbol budaya dan adat Batak yang sarat makna, cocok untuk koleksi dan upacara adat.", price: 450000, image: img("fas014"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s30, rating: 4.9, reviewCount: 145, soldCount: 310, stock: 20, weight: 600, tags: ["ulos", "batak", "tenun", "sumatera"] },
  { id: "fas015", name: "Kain Songket Palembang Premium", slug: "kain-songket-palembang", description: "Songket Palembang dengan benang emas asli, motif bunga cina. Warisan budaya Sumatera Selatan yang mewah dan elegan.", price: 875000, originalPrice: 1100000, image: img("fas015"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s30, rating: 4.9, reviewCount: 98, soldCount: 180, stock: 15, weight: 700, tags: ["songket", "palembang", "benang emas"], isFeatured: true },
  { id: "fas016", name: "Batik Mega Mendung Cirebon Tulis", slug: "batik-mega-mendung-cirebon", description: "Batik tulis mega mendung khas Cirebon dengan warna-warna cerah yang mencolok. Motif awan berlapis yang ikonik dan diakui UNESCO.", price: 380000, image: img("fas016"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s26, rating: 4.9, reviewCount: 321, soldCount: 760, stock: 35, weight: 300, tags: ["batik", "mega mendung", "cirebon", "tulis"] },
  { id: "fas017", name: "Selendang Tenun Lombok Sukarara", slug: "selendang-tenun-lombok", description: "Selendang tenun tangan dari Lombok Sukarara. Motif geometrik khas Lombok dengan warna-warna berani yang cantik.", price: 145000, image: img("fas017"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s19, rating: 4.7, reviewCount: 234, soldCount: 670, stock: 45, weight: 200, tags: ["selendang", "tenun", "lombok"] },
  { id: "fas018", name: "Sepatu Batik Handmade Wanita", slug: "sepatu-batik-handmade", description: "Sepatu wanita dilapisi kain batik tulis pilihan. Handmade, bahan kulit sintetis premium, nyaman dipakai seharian.", price: 285000, originalPrice: 345000, image: img("fas018"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s07, rating: 4.7, reviewCount: 234, soldCount: 540, stock: 30, weight: 800, tags: ["sepatu", "batik", "handmade", "wanita"] },
  { id: "fas019", name: "Tas Batik Anyam Rotan Wanita", slug: "tas-batik-anyam-rotan", description: "Tas wanita kolaborasi batik dan anyaman rotan. Desain unik memadukan motif batik Jawa dengan kerajinan rotan Bali.", price: 175000, image: img("fas019"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s11, rating: 4.8, reviewCount: 345, soldCount: 1200, stock: 50, weight: 600, tags: ["tas", "batik", "rotan", "wanita"] },
  { id: "fas020", name: "Kaos Tenun Bali Pantai Motif Barong", slug: "kaos-tenun-bali-barong", description: "Kaos pantai Bali dengan motif barong dan alam Bali yang ikonik. Bahan katun combed 30s, adem untuk iklim tropis.", price: 95000, image: img("fas020"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s11, rating: 4.7, reviewCount: 654, soldCount: 3400, stock: 200, weight: 200, tags: ["kaos", "bali", "barong"], isNew: true },
  { id: "fas021", name: "Celana Batik Santai Pria Jogger", slug: "celana-batik-jogger", description: "Celana jogger batik casual untuk pria dengan bahan katun halus. Desain modern, cocok untuk santai maupun jalan-jalan.", price: 135000, image: img("fas021"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.6, reviewCount: 312, soldCount: 1100, stock: 80, weight: 400, tags: ["celana", "batik", "jogger"] },
  { id: "fas022", name: "Daster Batik Wanita Motif Bunga", slug: "daster-batik-motif-bunga", description: "Daster batik wanita dengan motif bunga yang cantik dan warna-warna cerah. Bahan rayon adem, longgar, nyaman untuk di rumah.", price: 95000, image: img("fas022"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s18, rating: 4.7, reviewCount: 876, soldCount: 5600, stock: 200, weight: 300, tags: ["daster", "batik", "wanita"] },
  { id: "fas023", name: "Jas Batik Formal Pria", slug: "jas-batik-formal-pria", description: "Jas batik formal untuk pria yang elegan dan berkarakter. Bahan berkualitas dengan jahitan rapi, cocok untuk acara formal.", price: 650000, originalPrice: 800000, image: img("fas023"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s06, rating: 4.9, reviewCount: 156, soldCount: 340, stock: 20, weight: 1000, tags: ["jas", "batik", "formal", "pria"] },
  { id: "fas024", name: "Batik Pekalongan Tiga Negeri", slug: "batik-pekalongan-tiga-negeri", description: "Batik Pekalongan motif tiga negeri dengan kombinasi warna merah, biru, dan soga. Kain primissima 100% katun.", price: 520000, image: img("fas024"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s18, rating: 4.9, reviewCount: 189, soldCount: 410, stock: 25, weight: 300, tags: ["batik", "pekalongan", "tiga negeri"] },
  { id: "fas025", name: "Kebaya Encim Betawi Brocade", slug: "kebaya-encim-betawi", description: "Kebaya encim khas Betawi dengan bahan brocade yang indah. Kerah bulat, kancing depan, desain Peranakan yang khas Jakarta.", price: 295000, image: img("fas025"), category: "Fashion & Batik", categorySlug: "fashion-batik", seller: sellers.s28, rating: 4.8, reviewCount: 210, soldCount: 450, stock: 30, weight: 400, tags: ["kebaya", "encim", "betawi"] },

  // ── Kerajinan Tangan ─────────────────────────────────────────────────────────
  { id: "kra001", name: "Ukiran Kayu Jepara Panel Dinding Burung", slug: "ukiran-kayu-jepara-burung", description: "Panel dinding ukiran kayu jati pilihan dari Jepara. Motif burung merak dengan detail halus hasil pengerjaan pengrajin maestro.", price: 850000, originalPrice: 1100000, image: img("kra001"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s09, rating: 4.9, reviewCount: 213, soldCount: 340, stock: 20, weight: 2000, tags: ["ukiran", "kayu", "jepara", "jati"], isFeatured: true, isSponsored: true },
  { id: "kra002", name: "Gerabah Kasongan Yogyakarta Set 3 Pcs", slug: "gerabah-kasongan-set", description: "Set gerabah tanah liat dari Kasongan Yogyakarta. Terdiri dari vas besar, sedang, dan kecil dengan motif etnik Jawa.", price: 285000, image: img("kra002"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s25, rating: 4.8, reviewCount: 312, soldCount: 670, stock: 40, weight: 3000, tags: ["gerabah", "kasongan", "yogyakarta", "tanah liat"] },
  { id: "kra003", name: "Wayang Kulit Mini Arjuna Koleksi", slug: "wayang-kulit-mini-arjuna", description: "Wayang kulit Arjuna versi mini dari kulit sapi pilihan. Dikerjakan oleh dalang pengrajin wayang Solo, cocok untuk koleksi dan dekorasi.", price: 185000, originalPrice: 230000, image: img("kra003"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s06, rating: 4.8, reviewCount: 198, soldCount: 540, stock: 50, weight: 200, tags: ["wayang", "kulit", "solo", "koleksi"] },
  { id: "kra004", name: "Topeng Malangan Dewi Sekartaji", slug: "topeng-malangan-dewi-sekartaji", description: "Topeng Malangan kayu pule lukis tangan motif Dewi Sekartaji. Karya seni budaya Malang yang diakui sebagai warisan budaya.", price: 250000, image: img("kra004"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s02, rating: 4.9, reviewCount: 145, soldCount: 290, stock: 25, weight: 500, tags: ["topeng", "malang", "kayu", "seni"] },
  { id: "kra005", name: "Tas Rotan Bali Vintage Round", slug: "tas-rotan-bali-round", description: "Tas rotan bulat khas Bali dengan finishing natural yang cantik. Handmade oleh pengrajin rotan Bali, cocok untuk pantai dan kasual.", price: 175000, image: img("kra005"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s11, rating: 4.8, reviewCount: 543, soldCount: 1780, stock: 80, weight: 600, tags: ["tas", "rotan", "bali", "handmade"], isFeatured: true },
  { id: "kra006", name: "Anyaman Bambu Keranjang Buah Premium", slug: "anyaman-bambu-keranjang-buah", description: "Keranjang buah dari anyaman bambu pilihan. Dibuat secara tradisional oleh pengrajin Tasikmalaya dengan pola geometrik yang indah.", price: 95000, image: img("kra006"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s05, rating: 4.7, reviewCount: 321, soldCount: 1200, stock: 100, weight: 500, tags: ["anyaman", "bambu", "keranjang"] },
  { id: "kra007", name: "Perhiasan Perak Koto Gadang Cincin", slug: "perhiasan-perak-koto-gadang-cincin", description: "Cincin perak 925 asli dari Koto Gadang, Bukittinggi. Motif ukiran tangan khas Minang yang halus dan elegan, tersedia berbagai ukuran.", price: 195000, image: img("kra007"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s12, rating: 4.9, reviewCount: 287, soldCount: 890, stock: 60, weight: 20, tags: ["perak", "cincin", "bukittinggi", "minang"], isFeatured: true },
  { id: "kra008", name: "Lampu Hias Bambu Rotan Industrial", slug: "lampu-hias-bambu-rotan", description: "Lampu gantung hias dari kombinasi bambu dan rotan. Desain bohemian industrial yang trendi, cocok untuk rumah dan kafe.", price: 145000, originalPrice: 175000, image: img("kra008"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s20, rating: 4.7, reviewCount: 345, soldCount: 760, stock: 45, weight: 800, tags: ["lampu", "bambu", "rotan", "dekorasi"] },
  { id: "kra009", name: "Patung Budha Kayu Suar Bali", slug: "patung-budha-kayu-suar-bali", description: "Patung Buddha meditasi dari kayu suar alami Bali. Finishing natural oil, cocok untuk dekorasi rumah, spa, dan zen corner.", price: 325000, image: img("kra009"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s11, rating: 4.8, reviewCount: 178, soldCount: 340, stock: 25, weight: 2000, tags: ["patung", "buddha", "kayu", "bali"] },
  { id: "kra010", name: "Tapis Lampung Sulam Tangan", slug: "tapis-lampung-sulam", description: "Kain tapis Lampung tradisional dengan sulaman benang emas tangan. Warisan budaya Lampung yang kaya makna dan nilai seni tinggi.", price: 650000, image: img("kra010"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s17, rating: 4.9, reviewCount: 89, soldCount: 145, stock: 10, weight: 500, tags: ["tapis", "lampung", "sulam", "benang emas"] },
  { id: "kra011", name: "Piring Kayu Ukir Jepara Dekorasi", slug: "piring-kayu-ukir-jepara", description: "Piring kayu jati ukiran indah dari Jepara sebagai dekorasi dinding atau meja. Ukiran motif bunga dan daun yang rumit dan detail.", price: 225000, image: img("kra011"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s09, rating: 4.8, reviewCount: 215, soldCount: 420, stock: 35, weight: 600, tags: ["kayu", "ukir", "jepara", "dekorasi"] },
  { id: "kra012", name: "Keramik Lombok Guci Batik", slug: "keramik-lombok-guci-batik", description: "Guci keramik dari Lombok dengan motif batik yang dilukis tangan. Finishing glossy, cocok untuk vas bunga atau dekorasi ruangan.", price: 185000, image: img("kra012"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s10, rating: 4.7, reviewCount: 198, soldCount: 430, stock: 40, weight: 1000, tags: ["keramik", "lombok", "guci"] },
  { id: "kra013", name: "Cermin Ukir Jepara Frame Jati", slug: "cermin-ukir-jepara", description: "Cermin dinding dengan bingkai kayu jati ukiran tangan Jepara. Motif bunga klasik, ukuran 60x80cm, siap gantung.", price: 650000, originalPrice: 800000, image: img("kra013"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s09, rating: 4.9, reviewCount: 134, soldCount: 210, stock: 15, weight: 5000, tags: ["cermin", "ukir", "jepara", "jati"] },
  { id: "kra014", name: "Gelang Manik-manik Bali Etnik", slug: "gelang-manik-bali-etnik", description: "Gelang manik-manik handmade dari Bali dengan motif etnik. Kombinasi warna-warna cerah yang khas Bali, cocok untuk daily wear.", price: 35000, image: img("kra014"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s11, rating: 4.7, reviewCount: 654, soldCount: 4300, stock: 300, weight: 50, tags: ["gelang", "manik", "bali", "etnik"], isNew: true },
  { id: "kra015", name: "Kalung Batu Alam Jasper Merah", slug: "kalung-batu-alam-jasper", description: "Kalung batu alam jasper merah pilihan dengan tali kulit. Dipercaya memiliki energi positif, cocok untuk pemakai spiritual.", price: 125000, image: img("kra015"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s12, rating: 4.6, reviewCount: 287, soldCount: 870, stock: 80, weight: 100, tags: ["kalung", "batu alam", "jasper"] },
  { id: "kra016", name: "Miniatur Rumah Adat Joglo Jawa", slug: "miniatur-rumah-adat-joglo", description: "Miniatur rumah adat Joglo Jawa dari kayu pinus. Detail yang akurat dan rapi, cocok untuk souvenir, hadiah, atau dekorasi meja.", price: 155000, image: img("kra016"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s25, rating: 4.7, reviewCount: 213, soldCount: 560, stock: 50, weight: 600, tags: ["miniatur", "rumah adat", "joglo", "souvenir"] },
  { id: "kra017", name: "Tikar Mendong Anyam Tasikmalaya", slug: "tikar-mendong-tasikmalaya", description: "Tikar mendong anyaman halus dari Tasikmalaya. Alas duduk alami yang nyaman, ramah lingkungan, dan tahan lama.", price: 85000, image: img("kra017"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s05, rating: 4.6, reviewCount: 198, soldCount: 670, stock: 70, weight: 800, tags: ["tikar", "mendong", "tasikmalaya"] },
  { id: "kra018", name: "Ornamen Batok Kelapa Lukis Unik", slug: "ornamen-batok-kelapa-lukis", description: "Ornamen dekorasi dari batok kelapa yang dilukis tangan dengan motif pemandangan alam Indonesia. Unik dan ramah lingkungan.", price: 45000, image: img("kra018"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s20, rating: 4.5, reviewCount: 167, soldCount: 890, stock: 150, weight: 200, tags: ["batok", "kelapa", "dekorasi"] },
  { id: "kra019", name: "Tas Anyam Mendong Pandan Natural", slug: "tas-anyam-mendong-pandan", description: "Tas anyam dari daun mendong dan pandan kering. Ringan, kuat, ramah lingkungan, dan bernilai seni tinggi karya pengrajin Sunda.", price: 115000, image: img("kra019"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s05, rating: 4.7, reviewCount: 321, soldCount: 980, stock: 60, weight: 300, tags: ["tas", "mendong", "pandan", "anyam"] },
  { id: "kra020", name: "Frame Foto Bambu Natural Rustic", slug: "frame-foto-bambu-rustic", description: "Bingkai foto dari bambu asli dengan sentuhan rustic yang estetik. Tersedia ukuran 4R, 5R, dan 10R.", price: 35000, image: img("kra020"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s20, rating: 4.6, reviewCount: 432, soldCount: 2300, stock: 200, weight: 200, tags: ["frame", "bambu", "foto"] },
  { id: "kra021", name: "Boneka Wayang Golek Sunda Miniatur", slug: "boneka-wayang-golek-sunda", description: "Boneka wayang golek Sunda dalam ukuran mini, dikerjakan tangan dengan kostum lengkap. Souvenir dan koleksi budaya Jawa Barat.", price: 125000, image: img("kra021"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s07, rating: 4.8, reviewCount: 178, soldCount: 430, stock: 40, weight: 300, tags: ["wayang", "golek", "sunda", "souvenir"] },
  { id: "kra022", name: "Vas Bunga Tanah Liat Etnik", slug: "vas-bunga-tanah-liat-etnik", description: "Vas bunga dari tanah liat dengan motif etnik Nusantara. Cocok untuk bunga segar maupun kering, menambah estetika ruangan.", price: 75000, image: img("kra022"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s25, rating: 4.6, reviewCount: 287, soldCount: 760, stock: 80, weight: 700, tags: ["vas", "tanah liat", "etnik"] },
  { id: "kra023", name: "Karpet Tenun Flores NTT Motif Suku", slug: "karpet-tenun-flores-ntt", description: "Karpet tenun tangan dari Flores NTT dengan motif hewan dan tumbuhan khas suku Ngada. Setiap karpet unik dan berbeda.", price: 385000, image: img("kra023"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s08, rating: 4.9, reviewCount: 89, soldCount: 145, stock: 12, weight: 2000, tags: ["karpet", "tenun", "flores", "ntt"] },
  { id: "kra024", name: "Kaligrafi Kulit Kambing Premium", slug: "kaligrafi-kulit-kambing", description: "Kaligrafi Arab di atas kulit kambing asli dengan tulisan ayat Al-Quran pilihan. Dibingkai kayu ukir, cocok untuk hiasan masjid dan rumah.", price: 275000, image: img("kra024"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s15, rating: 4.8, reviewCount: 213, soldCount: 390, stock: 30, weight: 400, tags: ["kaligrafi", "kulit", "islami"] },
  { id: "kra025", name: "Meja Kayu Pallet Rustic Coffee Table", slug: "meja-kayu-pallet-rustic", description: "Meja kopi (coffee table) dari kayu pallet daur ulang. Desain industrial rustic yang estetik, finishing cat natural.", price: 550000, originalPrice: 700000, image: img("kra025"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s09, rating: 4.7, reviewCount: 156, soldCount: 280, stock: 15, weight: 8000, tags: ["meja", "kayu", "rustic", "pallet"] },
  { id: "kra026", name: "Hiasan Dinding Makrame Boho", slug: "hiasan-dinding-makrame", description: "Hiasan dinding makrame bohemian dari tali katun pilihan. Handmade dengan teknik simpul tradisional, estetik untuk dekorasi rumah.", price: 95000, image: img("kra026"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s20, rating: 4.7, reviewCount: 543, soldCount: 1890, stock: 100, weight: 300, tags: ["makrame", "boho", "dekorasi", "dinding"] },
  { id: "kra027", name: "Souvenir Pernikahan Kipas Batik Lucu", slug: "souvenir-pernikahan-kipas-batik", description: "Kipas batik cantik untuk souvenir pernikahan. Bisa kustomisasi nama dan tanggal pernikahan, minimum order 50 pcs.", price: 8500, image: img("kra027"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s06, rating: 4.8, reviewCount: 654, soldCount: 12000, stock: 1000, weight: 50, tags: ["souvenir", "pernikahan", "kipas", "batik"] },
  { id: "kra028", name: "Asbak Batu Andesit Alami", slug: "asbak-batu-andesit", description: "Asbak dari batu andesit alami yang kokoh dan tahan panas. Desain minimalis natural, cocok untuk meja kerja dan ruang tamu.", price: 55000, image: img("kra028"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s25, rating: 4.5, reviewCount: 198, soldCount: 670, stock: 80, weight: 500, tags: ["asbak", "batu", "andesit"] },
  { id: "kra029", name: "Pigura Batik Kayu Ukir Dekorasi", slug: "pigura-batik-kayu-ukir", description: "Pigura/bingkai foto dekoratif dengan kain batik tulis asli dan bingkai kayu ukir. Kombinasi seni batik dan ukir Jawa yang memukau.", price: 145000, image: img("kra029"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s09, rating: 4.8, reviewCount: 234, soldCount: 560, stock: 40, weight: 500, tags: ["pigura", "batik", "kayu", "ukir"] },
  { id: "kra030", name: "Tempat Lilin Kayu Teak Minimalis", slug: "tempat-lilin-kayu-teak", description: "Tempat lilin dari kayu jati mini dengan desain minimalis Skandinavia. Finishing minyak natural, cocok untuk dekorasi meja makan.", price: 65000, image: img("kra030"), category: "Kerajinan Tangan", categorySlug: "kerajinan-tangan", seller: sellers.s09, rating: 4.7, reviewCount: 312, soldCount: 870, stock: 100, weight: 200, tags: ["tempat lilin", "kayu", "minimalis"] },

  // ── Kecantikan ───────────────────────────────────────────────────────────────
  { id: "kec001", name: "Lulur Beras Kencur Tradisional Jawa", slug: "lulur-beras-kencur-tradisional", description: "Lulur beras kencur tradisional resep leluhur Jawa. Mengangkat sel kulit mati, mencerahkan, dan membuat kulit harum alami.", price: 35000, image: img("kec001"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.8, reviewCount: 876, soldCount: 5400, stock: 300, weight: 200, tags: ["lulur", "beras kencur", "herbal", "kulit"], isFeatured: true },
  { id: "kec002", name: "Sabun Herbal Kunyit Cerahkan Kulit", slug: "sabun-herbal-kunyit", description: "Sabun mandi herbal dengan ekstrak kunyit murni. Mencerahkan kulit, anti bakteri, cocok untuk semua jenis kulit termasuk sensitif.", price: 18000, image: img("kec002"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.7, reviewCount: 1234, soldCount: 8900, stock: 500, weight: 100, tags: ["sabun", "kunyit", "herbal", "cerah"] },
  { id: "kec003", name: "Minyak Kemiri Hitamkan Rambut Alami", slug: "minyak-kemiri-hitamkan-rambut", description: "Minyak kemiri 100% murni untuk menghitamkan rambut secara alami. Mengurangi uban, mengatasi kerontokan, dan melembabkan rambut.", price: 42000, originalPrice: 55000, image: img("kec003"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.8, reviewCount: 987, soldCount: 6700, stock: 250, weight: 100, tags: ["minyak", "kemiri", "rambut", "herbal"], isFeatured: true },
  { id: "kec004", name: "Masker Wajah Bengkoang Putih Alami", slug: "masker-wajah-bengkoang", description: "Masker wajah ekstrak bengkoang segar untuk mencerahkan kulit secara alami. Formula tanpa bleaching, aman dipakai rutin.", price: 28000, image: img("kec004"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.7, reviewCount: 765, soldCount: 5600, stock: 400, weight: 100, tags: ["masker", "bengkoang", "cerah", "wajah"] },
  { id: "kec005", name: "Serum Vitamin C Aloe Vera 30ml", slug: "serum-vitamin-c-aloe-vera", description: "Serum wajah vitamin C dengan ekstrak aloe vera murni. Mencerahkan, antioksidan, mengurangi kerutan, cocok pagi dan malam.", price: 65000, originalPrice: 85000, image: img("kec005"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.8, reviewCount: 1123, soldCount: 4300, stock: 200, weight: 50, tags: ["serum", "vitamin c", "wajah"], isNew: true },
  { id: "kec006", name: "Krim Wajah Lidah Buaya Night Cream", slug: "krim-wajah-lidah-buaya", description: "Krim malam lidah buaya yang melembabkan dan meregenerasi kulit saat tidur. Formulasi herbal tanpa paraben.", price: 48000, image: img("kec006"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.6, reviewCount: 543, soldCount: 3200, stock: 300, weight: 50, tags: ["krim", "lidah buaya", "night cream"] },
  { id: "kec007", name: "Shampoo Herbal Seledri Anti Rontok", slug: "shampoo-herbal-seledri", description: "Shampo herbal ekstrak seledri untuk mengatasi rambut rontok dan memperkuat akar rambut. Formula mild, cocok untuk keramas setiap hari.", price: 38000, image: img("kec007"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.7, reviewCount: 654, soldCount: 4100, stock: 250, weight: 200, tags: ["shampoo", "seledri", "herbal", "anti rontok"] },
  { id: "kec008", name: "Body Lotion Susu Kambing Premium", slug: "body-lotion-susu-kambing", description: "Body lotion susu kambing murni untuk kulit super lembab dan halus. Mengandung asam lamat alami, cocok untuk kulit kering.", price: 55000, image: img("kec008"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.8, reviewCount: 876, soldCount: 5600, stock: 300, weight: 200, tags: ["lotion", "susu kambing", "kulit"] },
  { id: "kec009", name: "Lulur Kopi Robusta Body Scrub", slug: "lulur-kopi-robusta-scrub", description: "Body scrub kopi robusta yang eksfoliasi efektif. Menghilangkan sel kulit mati, menyegarkan, aroma kopi yang khas.", price: 45000, image: img("kec009"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.7, reviewCount: 765, soldCount: 4500, stock: 250, weight: 200, tags: ["lulur", "kopi", "scrub"] },
  { id: "kec010", name: "Sabun Arang Aktif Detox Wajah", slug: "sabun-arang-aktif-detox", description: "Sabun batang arang aktif (activated charcoal) untuk membersihkan pori dan detoks wajah. Anti bakteri, cocok kulit berminyak.", price: 22000, image: img("kec010"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.6, reviewCount: 543, soldCount: 4300, stock: 400, weight: 100, tags: ["sabun", "arang aktif", "charcoal", "wajah"] },
  { id: "kec011", name: "Toner Mawar Organik Rose Water", slug: "toner-mawar-organik", description: "Toner air mawar organik murni tanpa alkohol. Menyeimbangkan pH kulit, melembabkan, dan menyegarkan setelah cuci muka.", price: 35000, image: img("kec011"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.7, reviewCount: 654, soldCount: 5100, stock: 300, weight: 100, tags: ["toner", "mawar", "organik"], isNew: true },
  { id: "kec012", name: "Minyak Zaitun Extra Virgin Cold Press", slug: "minyak-zaitun-extra-virgin", description: "Minyak zaitun extra virgin cold press untuk perawatan rambut dan kulit. Serbaguna, melembabkan, dan kaya vitamin E alami.", price: 75000, originalPrice: 95000, image: img("kec012"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.8, reviewCount: 432, soldCount: 2900, stock: 150, weight: 200, tags: ["minyak zaitun", "olive oil", "kulit"] },
  { id: "kec013", name: "Lip Balm Madu Lebah Hutan SPF15", slug: "lip-balm-madu-lebah", description: "Lip balm dengan madu lebah hutan asli dan SPF15. Melembabkan bibir pecah-pecah, alami, tidak berminyak.", price: 15000, image: img("kec013"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s14, rating: 4.7, reviewCount: 876, soldCount: 7800, stock: 500, weight: 20, tags: ["lip balm", "madu", "bibir"] },
  { id: "kec014", name: "Parfum Bunga Melati Eau de Parfum", slug: "parfum-bunga-melati", description: "Parfum dengan dominan aroma melati segar khas Indonesia. Formula EDP tahan 8-10 jam, botol elegan.", price: 95000, image: img("kec014"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.7, reviewCount: 321, soldCount: 1800, stock: 100, weight: 100, tags: ["parfum", "melati", "edp"] },
  { id: "kec015", name: "Deodoran Tawas Alami Antiperspirant", slug: "deodoran-tawas-alami", description: "Deodoran tawas (alum) alami bebas aluminium klorida dan paraben. Efektif 24 jam, tidak meninggalkan noda di baju.", price: 20000, image: img("kec015"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.6, reviewCount: 543, soldCount: 4300, stock: 500, weight: 100, tags: ["deodoran", "tawas", "alami"] },
  { id: "kec016", name: "Sunscreen Herbal SPF50 PA+++ 50ml", slug: "sunscreen-herbal-spf50", description: "Sunscreen herbal SPF50 PA+++ dengan ekstrak daun teh hijau dan centella. Ringan, tidak lengket, cocok untuk kulit tropis.", price: 85000, originalPrice: 110000, image: img("kec016"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.8, reviewCount: 765, soldCount: 3400, stock: 200, weight: 80, tags: ["sunscreen", "spf50", "herbal"], isFeatured: true },
  { id: "kec017", name: "Masker Rambut Alpukat Argan Oil", slug: "masker-rambut-alpukat-argan", description: "Masker rambut kaya protein dari alpukat dan argan oil. Melembabkan, memperkuat, dan memberi kilap pada rambut rusak.", price: 48000, image: img("kec017"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.7, reviewCount: 432, soldCount: 2800, stock: 250, weight: 200, tags: ["masker", "rambut", "alpukat", "argan"] },
  { id: "kec018", name: "Minyak Esensial Lavender 10ml", slug: "minyak-esensial-lavender", description: "Minyak esensial lavender 100% murni untuk aromaterapi dan perawatan. Menenangkan, anti stres, membantu tidur lebih nyenyak.", price: 45000, image: img("kec018"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s13, rating: 4.8, reviewCount: 654, soldCount: 4100, stock: 300, weight: 30, tags: ["minyak esensial", "lavender", "aromaterapi"] },
  { id: "kec019", name: "Handbody Temulawak Glow & Bright", slug: "handbody-temulawak-glow", description: "Body lotion temulawak untuk mencerahkan dan meratakan warna kulit. Formula cepat meresap, tidak lengket, aroma segar.", price: 38000, image: img("kec019"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s22, rating: 4.6, reviewCount: 543, soldCount: 4300, stock: 300, weight: 200, tags: ["handbody", "temulawak", "cerah"] },
  { id: "kec020", name: "Masker Lempung Bentonit Deep Clean", slug: "masker-lempung-bentonit", description: "Masker wajah bentonit clay untuk membersihkan pori secara mendalam. Menyerap minyak berlebih, efektif untuk kulit berminyak.", price: 32000, image: img("kec020"), category: "Kecantikan", categorySlug: "kecantikan", seller: sellers.s21, rating: 4.7, reviewCount: 432, soldCount: 3800, stock: 300, weight: 100, tags: ["masker", "clay", "bentonit", "pori"] },

  // ── Agro & Herbal ────────────────────────────────────────────────────────────
  { id: "agr001", name: "Madu Hutan Kalimantan Murni 500gr", slug: "madu-hutan-kalimantan-murni", description: "Madu hutan lebah liar dari Kalimantan yang tidak dipanaskan (raw honey). Kaya enzim, vitamin, dan antioksidan alami.", price: 185000, originalPrice: 230000, image: img("agr001"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s14, rating: 4.9, reviewCount: 876, soldCount: 3400, stock: 100, weight: 500, tags: ["madu", "hutan", "kalimantan", "raw honey"], isFeatured: true, isSponsored: true },
  { id: "agr002", name: "Jahe Merah Bubuk Premium 100gr", slug: "jahe-merah-bubuk-premium", description: "Jahe merah kering bubuk pilihan dari petani Jawa. Tinggi gingerol, menghangatkan tubuh, meningkatkan imunitas.", price: 35000, image: img("agr002"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s22, rating: 4.8, reviewCount: 765, soldCount: 6700, stock: 300, weight: 100, tags: ["jahe merah", "bubuk", "herbal"] },
  { id: "agr003", name: "Temulawak Simplisia Kering Organik", slug: "temulawak-simplisia-kering", description: "Temulawak kering organik tanpa pestisida dari petani Jawa. Untuk jamu, minuman kesehatan, dan suplemen alami.", price: 28000, image: img("agr003"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s13, rating: 4.7, reviewCount: 432, soldCount: 4300, stock: 300, weight: 100, tags: ["temulawak", "simplisia", "organik"] },
  { id: "agr004", name: "Kunyit Asam Instant Jamu Tradisional", slug: "kunyit-asam-instant-jamu", description: "Kunyit asam instan serbuk tradisional. Minuman kesehatan untuk menjaga stamina, melancarkan haid, dan detoks alami.", price: 25000, image: img("agr004"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s22, rating: 4.7, reviewCount: 654, soldCount: 5600, stock: 400, weight: 100, tags: ["kunyit asam", "jamu", "instan"] },
  { id: "agr005", name: "Propolis Lebah Murni Kalimantan 30ml", slug: "propolis-lebah-murni-kalimantan", description: "Propolis murni dari lebah Kalimantan dengan kadar flavonoid tinggi. Anti bakteri alami, meningkatkan imunitas, antibiotik alami.", price: 125000, originalPrice: 155000, image: img("agr005"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s14, rating: 4.9, reviewCount: 543, soldCount: 1800, stock: 100, weight: 50, tags: ["propolis", "lebah", "imunitas"] },
  { id: "agr006", name: "Kayu Manis Batang Ceylon Premium 100gr", slug: "kayu-manis-batang-ceylon", description: "Kayu manis batang Ceylon (true cinnamon) berkualitas tinggi. Aroma lebih halus dibanding cassia, aman dikonsumsi lebih banyak.", price: 45000, image: img("agr006"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s15, rating: 4.8, reviewCount: 345, soldCount: 2900, stock: 200, weight: 100, tags: ["kayu manis", "ceylon", "rempah"] },
  { id: "agr007", name: "Minyak Kelapa Murni VCO Cold Press 250ml", slug: "minyak-kelapa-murni-vco", description: "VCO (Virgin Coconut Oil) cold press murni tanpa dipanaskan. Kaya asam laurat, untuk masak sehat, perawatan kulit dan rambut.", price: 65000, image: img("agr007"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s15, rating: 4.8, reviewCount: 654, soldCount: 3400, stock: 200, weight: 250, tags: ["VCO", "minyak kelapa", "cold press"] },
  { id: "agr008", name: "Daun Kelor Kapsul Organik 60 Kapsul", slug: "daun-kelor-kapsul-organik", description: "Kapsul daun kelor (moringa) organik. Superfood tinggi protein, 7x vitamin C jeruk, 4x kalsium susu, untuk energi dan imunitas.", price: 75000, image: img("agr008"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s13, rating: 4.8, reviewCount: 543, soldCount: 2800, stock: 200, weight: 100, tags: ["daun kelor", "moringa", "superfood", "kapsul"] },
  { id: "agr009", name: "Jintan Hitam Habbatus Sauda 500gr", slug: "jintan-hitam-habbatus-sauda", description: "Jintan hitam (habbatus sauda) premium dari Turki. Obat untuk segala penyakit kecuali mati, sesuai hadis. Biji utuh terpilih.", price: 85000, image: img("agr009"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s13, rating: 4.9, reviewCount: 765, soldCount: 4100, stock: 200, weight: 500, tags: ["jintan hitam", "habbatus sauda", "herbal"], isFeatured: true },
  { id: "agr010", name: "Gula Merah Aren Organik 500gr", slug: "gula-merah-aren-organik", description: "Gula merah aren organik dari nira segar perkebunan aren Jawa. Indeks glikemik lebih rendah dari gula pasir, manis alami.", price: 28000, image: img("agr010"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s16, rating: 4.7, reviewCount: 432, soldCount: 4300, stock: 300, weight: 500, tags: ["gula merah", "aren", "organik"] },
  { id: "agr011", name: "Rempah Rendang Komplit Set 1 kg", slug: "rempah-rendang-komplit-set", description: "Set rempah lengkap untuk memasak rendang Padang autentik. 20+ rempah dipilih dan ditakar oleh chef spesialis masakan Padang.", price: 65000, image: img("agr011"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s01, rating: 4.9, reviewCount: 654, soldCount: 3400, stock: 150, weight: 200, tags: ["rempah", "rendang", "padang"] },
  { id: "agr012", name: "Akar Bajakah Kalimantan Asli", slug: "akar-bajakah-kalimantan", description: "Akar bajakah dari hutan Kalimantan yang dikenal sebagai tanaman tradisional penyembuh. Rebus sebagai teh atau kapsul.", price: 95000, image: img("agr012"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s14, rating: 4.7, reviewCount: 345, soldCount: 1800, stock: 100, weight: 200, tags: ["bajakah", "kalimantan", "herbal"], isNew: true },
  { id: "agr013", name: "Royal Jelly Segar Lebah 100gr", slug: "royal-jelly-segar-lebah", description: "Royal jelly segar dari lebah ratu. Kaya protein, vitamin, dan hormon alami untuk meningkatkan stamina dan vitalitas.", price: 175000, image: img("agr013"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s14, rating: 4.8, reviewCount: 213, soldCount: 560, stock: 50, weight: 100, tags: ["royal jelly", "lebah", "stamina"] },
  { id: "agr014", name: "Kulit Manggis Kapsul 60 Kapsul", slug: "kulit-manggis-kapsul", description: "Kapsul ekstrak kulit manggis dengan kandungan xanthone tinggi. Antioksidan kuat, anti kanker, meningkatkan imunitas.", price: 65000, image: img("agr014"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s22, rating: 4.7, reviewCount: 432, soldCount: 2900, stock: 200, weight: 100, tags: ["kulit manggis", "xanthone", "kapsul"] },
  { id: "agr015", name: "Bibit Tanaman Hias Succulent Set 6", slug: "bibit-succulent-set-6", description: "Set 6 bibit succulent berbagai jenis dalam pot mini cantik. Mudah dirawat, tahan kering, cocok untuk dekorasi meja dan rumah.", price: 85000, image: img("agr015"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s13, rating: 4.8, reviewCount: 543, soldCount: 2800, stock: 100, weight: 1000, tags: ["succulent", "tanaman hias", "bibit"], isNew: true },
  { id: "agr016", name: "Sari Kurma Premium Madinah 500ml", slug: "sari-kurma-premium-madinah", description: "Sari kurma ajwa asli Madinah dalam kemasan botol siap minum. Tinggi energi, penambah darah, dan kekuatan fisik.", price: 95000, image: img("agr016"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s13, rating: 4.8, reviewCount: 432, soldCount: 2200, stock: 150, weight: 500, tags: ["kurma", "sari kurma", "madinah"] },
  { id: "agr017", name: "Madu Trigona Kelulut Sulawesi 250gr", slug: "madu-trigona-kelulut-sulawesi", description: "Madu kelulut (trigona) dari Sulawesi dengan rasa asam manis khas. Lebih tinggi kandungan propolis dan antioksidan dari madu biasa.", price: 155000, image: img("agr017"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s15, rating: 4.8, reviewCount: 321, soldCount: 1200, stock: 80, weight: 250, tags: ["madu", "trigona", "kelulut", "sulawesi"] },
  { id: "agr018", name: "Sambiloto Herbal Kapsul 60 Kapsul", slug: "sambiloto-herbal-kapsul", description: "Kapsul sambiloto (Andrographis paniculata) untuk antibiotik alami dan anti inflamasi. Efektif untuk batuk, demam, dan infeksi.", price: 45000, image: img("agr018"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s22, rating: 4.6, reviewCount: 287, soldCount: 1800, stock: 200, weight: 100, tags: ["sambiloto", "herbal", "kapsul"] },
  { id: "agr019", name: "Cengkeh Premium Grade A Maluku 100gr", slug: "cengkeh-premium-grade-a-maluku", description: "Cengkeh kering kualitas A dari Maluku, pusat cengkeh dunia. Aroma intens, cocok untuk memasak, kopi, dan pengobatan.", price: 38000, image: img("agr019"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s15, rating: 4.8, reviewCount: 213, soldCount: 2100, stock: 200, weight: 100, tags: ["cengkeh", "maluku", "rempah"] },
  { id: "agr020", name: "Serai Kering Organik Bubuk 50gr", slug: "serai-kering-organik-bubuk", description: "Serai organik dikeringkan dan digiling halus. Untuk bumbu masak, teh serai, dan aromaterapi. Aroma segar dan kuat.", price: 22000, image: img("agr020"), category: "Agro & Herbal", categorySlug: "agro-herbal", seller: sellers.s13, rating: 4.6, reviewCount: 213, soldCount: 2800, stock: 300, weight: 50, tags: ["serai", "organik", "bumbu"] },

  // ── Elektronik Lokal ─────────────────────────────────────────────────────────
  { id: "ele001", name: "Power Bank 20000mAh Fast Charge 22.5W", slug: "power-bank-20000mah-fast-charge", description: "Power bank 20000mAh dengan fast charge 22.5W. Mendukung USB-C dan Micro USB, LED indicator, bodi slim anti gores.", price: 185000, originalPrice: 240000, image: img("ele001"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.6, reviewCount: 876, soldCount: 3400, stock: 200, weight: 400, tags: ["power bank", "fast charge", "20000mah"], isFeatured: true },
  { id: "ele002", name: "Earphone TWS Bluetooth 5.3 ANC", slug: "earphone-tws-bluetooth-anc", description: "Earphone true wireless stereo dengan Active Noise Cancellation. Baterai 6jam + case 24jam, tahan air IPX5, bass kuat.", price: 245000, image: img("ele002"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.5, reviewCount: 654, soldCount: 1800, stock: 150, weight: 100, tags: ["earphone", "tws", "bluetooth", "anc"] },
  { id: "ele003", name: "Charger GaN 65W 3-Port USB-C + USB-A", slug: "charger-gan-65w-3-port", description: "Charger GaN (Gallium Nitride) 65W tiga port. Lebih kecil dari charger laptop biasa, kompatibel laptop, tablet, dan HP.", price: 195000, originalPrice: 250000, image: img("ele003"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.7, reviewCount: 543, soldCount: 2100, stock: 200, weight: 100, tags: ["charger", "GaN", "65W", "fast charge"], isNew: true },
  { id: "ele004", name: "Kabel Data Braided USB-C to USB-C 2m", slug: "kabel-data-usbc-braided-2m", description: "Kabel USB-C to USB-C nylon braided 2 meter. Dukung PD 100W, transfer data 10Gbps, bending 30.000 kali tanpa putus.", price: 45000, image: img("ele004"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.6, reviewCount: 876, soldCount: 5600, stock: 500, weight: 100, tags: ["kabel", "USB-C", "braided"] },
  { id: "ele005", name: "Lampu LED Smart WiFi 10W RGB Alexa", slug: "lampu-led-smart-wifi-rgb", description: "Lampu LED pintar 10W RGB 16 juta warna. Kontrol via smartphone atau suara (Alexa/Google), bisa atur jadwal dan scene.", price: 65000, image: img("ele005"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.5, reviewCount: 543, soldCount: 2800, stock: 300, weight: 100, tags: ["lampu", "smart", "LED", "RGB", "WiFi"] },
  { id: "ele006", name: "Speaker Bluetooth Portable Outdoor 20W", slug: "speaker-bluetooth-portable-outdoor", description: "Speaker Bluetooth 20W dengan bass kuat dan waterproof IPX7. Baterai 10 jam, radius koneksi 30 meter, cocok outdoor.", price: 285000, originalPrice: 350000, image: img("ele006"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.6, reviewCount: 432, soldCount: 1200, stock: 100, weight: 500, tags: ["speaker", "bluetooth", "portable", "outdoor"] },
  { id: "ele007", name: "Ring Light LED 10 Inch Tripod Lipat", slug: "ring-light-led-10-inch-tripod", description: "Ring light LED 10 inch dengan tripod lipat teleskopik. 3 mode cahaya, 10 level kecerahan, cocok untuk konten creator.", price: 125000, image: img("ele007"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.6, reviewCount: 654, soldCount: 2900, stock: 200, weight: 600, tags: ["ring light", "LED", "konten creator"], isNew: true },
  { id: "ele008", name: "USB Hub 7-in-1 Type-C Docking Station", slug: "usb-hub-7in1-type-c-docking", description: "USB hub 7-in-1 dengan port: HDMI 4K, 3x USB-A, SD card, TF card, dan PD 100W. Plug and play tanpa driver.", price: 175000, image: img("ele008"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.5, reviewCount: 345, soldCount: 980, stock: 150, weight: 200, tags: ["USB hub", "docking", "HDMI", "type-C"] },
  { id: "ele009", name: "Mouse Wireless Ergonomis Silent Click", slug: "mouse-wireless-ergonomis-silent", description: "Mouse wireless ergonomis dengan klik senyap (silent). Baterai AA tahan 12 bulan, DPI adjustable, kompatibel semua OS.", price: 95000, image: img("ele009"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.6, reviewCount: 543, soldCount: 2100, stock: 200, weight: 150, tags: ["mouse", "wireless", "ergonomis", "silent"] },
  { id: "ele010", name: "Webcam HD 1080p Autofocus Stereo Mic", slug: "webcam-hd-1080p-autofocus", description: "Webcam 1080p 30fps dengan autofocus dan mikrofon stereo built-in. Plug and play USB, cocok untuk WFH dan video call.", price: 245000, originalPrice: 300000, image: img("ele010"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.5, reviewCount: 345, soldCount: 870, stock: 100, weight: 200, tags: ["webcam", "1080p", "autofocus", "WFH"] },
  { id: "ele011", name: "Tripod HP Flexible Gorilla 35cm", slug: "tripod-hp-flexible-gorilla", description: "Tripod kaki fleksibel (gorilla pod) untuk HP. Kaki bisa dilipat dan diikat di mana saja, kepala bisa putar 360°.", price: 55000, image: img("ele011"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.5, reviewCount: 765, soldCount: 4300, stock: 300, weight: 200, tags: ["tripod", "gorilla", "flexible", "HP"] },
  { id: "ele012", name: "Memory Card 128GB Class 10 UHS-I", slug: "memory-card-128gb-class10", description: "Micro SD 128GB Class 10 UHS-I kecepatan baca 100MB/s. Cocok untuk HP, kamera, drone. Tahan air, suhu, dan magnet.", price: 85000, originalPrice: 110000, image: img("ele012"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.5, reviewCount: 654, soldCount: 3400, stock: 300, weight: 20, tags: ["memory card", "microSD", "128GB"] },
  { id: "ele013", name: "Holder HP Mobil Magnetic Universal", slug: "holder-hp-mobil-magnetic", description: "Holder HP mobil dengan magnet kuat 360° rotate. Universal untuk semua HP, dudukan dashboard dan kaca depan.", price: 35000, image: img("ele013"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.6, reviewCount: 1123, soldCount: 7800, stock: 500, weight: 100, tags: ["holder", "HP", "mobil", "magnetic"] },
  { id: "ele014", name: "Keyboard Mechanical Mini 68-Key TKL", slug: "keyboard-mechanical-mini-tkl", description: "Keyboard mechanical tenkeyless 68 tombol dengan switch blue. RGB backlight, kabel detachable USB-C, cocok untuk gaming.", price: 295000, image: img("ele014"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.5, reviewCount: 213, soldCount: 540, stock: 80, weight: 700, tags: ["keyboard", "mechanical", "gaming", "RGB"], isNew: true },
  { id: "ele015", name: "Cooling Pad Laptop 6 Fan LED Blue", slug: "cooling-pad-laptop-6-fan", description: "Cooling pad laptop dengan 6 kipas efisien dan lampu LED biru. Cocok untuk laptop 14-17 inch, 2 port USB tambahan.", price: 125000, image: img("ele015"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.4, reviewCount: 432, soldCount: 1800, stock: 150, weight: 600, tags: ["cooling pad", "laptop", "kipas"] },
  { id: "ele016", name: "Flash Drive OTG 3-in-1 64GB", slug: "flash-drive-otg-64gb", description: "USB flash drive OTG 64GB dengan 3 konektor: USB-A, USB-C, dan Lightning. Kompatibel Android, iPhone, dan komputer.", price: 65000, image: img("ele016"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.5, reviewCount: 543, soldCount: 2800, stock: 300, weight: 30, tags: ["flash drive", "OTG", "64GB"] },
  { id: "ele017", name: "Adaptor Travel Universal 200 Negara", slug: "adaptor-travel-universal", description: "Adaptor travel universal untuk digunakan di 200+ negara. 4 USB + 1 USB-C, total output 65W, compact dan ringan.", price: 155000, image: img("ele017"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.5, reviewCount: 287, soldCount: 980, stock: 100, weight: 150, tags: ["adaptor", "travel", "universal"] },
  { id: "ele018", name: "Screen Protector Anti Glare Tempered Glass", slug: "screen-protector-anti-glare", description: "Tempered glass anti glare 0.33mm untuk HP iPhone/Samsung/Xiaomi. Pelindung layar dari goresan, ujung bulat 2.5D.", price: 25000, image: img("ele018"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.5, reviewCount: 1234, soldCount: 8900, stock: 500, weight: 50, tags: ["screen protector", "tempered glass", "anti glare"] },
  { id: "ele019", name: "Case HP Anti Shock Custom Print", slug: "case-hp-anti-shock-custom", description: "Softcase HP anti shock custom desain. Tersedia untuk iPhone, Samsung, Xiaomi, Oppo, dan Vivo. Bisa request desain sendiri.", price: 45000, image: img("ele019"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s29, rating: 4.6, reviewCount: 876, soldCount: 5600, stock: 500, weight: 50, tags: ["case", "HP", "anti shock", "custom"] },
  { id: "ele020", name: "Baterai AA Rechargeable NiMH 2800mAh 4 pcs", slug: "baterai-aa-rechargeable-nimh", description: "Baterai AA isi ulang NiMH 2800mAh 4 buah. Bisa diisi ulang 1000x, lebih hemat dari baterai sekali pakai.", price: 75000, image: img("ele020"), category: "Elektronik Lokal", categorySlug: "elektronik-lokal", seller: sellers.s23, rating: 4.6, reviewCount: 321, soldCount: 1560, stock: 200, weight: 100, tags: ["baterai", "rechargeable", "AA", "NiMH"] },
];

// ── Categories ────────────────────────────────────────────────────────────────

export const categories: Category[] = [
  { name: "Makanan & Minuman", slug: "makanan-minuman", icon: "🍱", count: 40 },
  { name: "Fashion & Batik", slug: "fashion-batik", icon: "👗", count: 25 },
  { name: "Kerajinan Tangan", slug: "kerajinan-tangan", icon: "🏺", count: 30 },
  { name: "Kecantikan", slug: "kecantikan", icon: "💄", count: 20 },
  { name: "Agro & Herbal", slug: "agro-herbal", icon: "🌿", count: 20 },
  { name: "Elektronik Lokal", slug: "elektronik-lokal", icon: "🔌", count: 20 },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter((p) => p.categorySlug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getSponsoredProducts(): Product[] {
  return products.filter((p) => p.isSponsored);
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.seller.city.toLowerCase().includes(q)
  );
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
